// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

public partial class Livro
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("livroNome")]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Nome Livro")]
    public string LivroNome { get; set; }

    [Required]
    [Column("livroAutor")]
    [StringLength(200)]
    [Unicode(false)]
    [Display(Name = "Autor")]
    public string LivroAutor { get; set; }

    [Required]
    [Column("livroEditora")]
    [StringLength(100)]
    [Unicode(false)]
    [Display(Name = "Editora")]
    public string LivroEditora { get; set; }

    [Column("livroAnoPublicacao", TypeName = "datetime")]
    [Display(Name = "Ano Publicação")]
    public DateTime LivroAnoPublicacao { get; set; }

    [Column("livroEdicao")]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Edição")]

    public string LivroEdicao { get; set; }

    [InverseProperty("LceIdLivroNavigation")]
    public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; } = new List<LivroClienteEmprestimo>();
}