// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

[Keyless]
public partial class VwLivroClienteEmprestimo
{
    [Required]
    [Column("cliCPF")]
    [StringLength(14)]
    [Unicode(false)]
    public string CliCpf { get; set; }

    [Required]
    [Column("cliNome")]
    [StringLength(200)]
    [Unicode(false)]
    public string CliNome { get; set; }

    [Required]
    [Column("livroNome")]
    [StringLength(50)]
    [Unicode(false)]
    public string LivroNome { get; set; }

    [Key]
    [Column("id")]
    public int Id { get; set; }

    public int? LceIdCliente { get; set; }

    public int? LceIdLivro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LceDataEmprestimo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LceDataEntrega { get; set; }

    public bool? LceEntregue { get; set; }
}